from math import sin,cos,tan,atan,pi
#tworz zmienna x
x=pi
b=0
#obilcz wartosci funkcji trygonometrycznych
print("Pi=0, kąt zero stopni: ")
print("sin(%f)%f" % (b,sin(b)))
print("cos(%f)%f" % (b,cos(b)))
print("tan(%f)%f" % (b,tan(b)))
print("ctan nie istnieje")
print("----------------------")
print("Pi/6, kąt trzydzieści stopni: ")
print("sin(%f)%f" % (x,sin(x/6)))
print("cos(%f)%f" % (x,cos(x/6)))
print("tan(%f)%f" % (x,tan(x/6)))
print("ctan(%f)%f"% (x,atan(x/6)))
print("----------------------")
print("Pi/4, kąt czterdzieści pięć stopni: ")
print("sin(%f)%f" % (x,sin(x/4)))
print("cos(%f)%f" % (x,cos(x/4)))
print("tan(%f)%f" % (x,tan(x/4)))
print("ctan(%f)%f"% (x,atan(x/4)))
print("----------------------")
print("Pi/3, kąt sześdziesiąt stopni: ")
print("sin(%f)%f" % (x,sin(x/3)))
print("cos(%f)%f" % (x,cos(x/3)))
print("tan(%f)%f" % (x,tan(x/3)))
print("ctan(%f)%f"% (x,atan(x/3)))
print("----------------------")
print("Pi/2, kąt dziewięćdziesiąt stopni: ")
print("sin(%f)%f" % (x,sin(x/2)))
print("cos(%f)%f" % (x,cos(x/2)))
print("tan(%f)%f - nie istnieje" % (x,tan(x/2)))
print("ctan(%f)%f"% (x,atan(x/2)))
print("----------------------")
